mac_address: AA:AA:AA:AA:AA:AA
stand_height: 1200
sit_height: 620
height_tolerance: 2.0
scan_timeout: 5
connection_timeout: 10
movement_timeout: 30
adapter_name: hci0
server_address: '127.0.0.1'
server_port: 9123
mqtt_broker: '127.0.0.1'
mqtt_port: 1883
mqtt_username: ""
mqtt_password: ""
